default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: consultorio_ESmileProject_development

test:
  <<: *default
  database: consultorio_ESmileProject_test

actions:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV.fetch('PG_DATABASE', 'postgres') %>
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'password') %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>

production:
  <<: *default
  database: consultorio_ESmileProject_production
  username: consultorio_ESmileProject
  password: <%= ENV["CONSULTORIO_ESMILEPROJECT_DATABASE_PASSWORD"] %>
